/*********************************************************************************  	 	 	 	 	 	 	 	 	 	 	
	
** The contents of this file are subject to the vtiger CRM Public License Version 1.0 	
 * ("License"); You may not use this file except in compliance with the License 	
 * The Original Code is:  vtiger CRM Open Source 	
 * The Initial Developer of the Original Code is vtiger. 	
 * Portions created by vtiger are Copyright (C) vtiger. 	
 * All Rights Reserved. 	
 ********************************************************************************/ 	
	
  	
var alert_arr = {        	
								NTIS_FORWARD:'Chuyển tiếp', 	
								NTIS_QUALIFY:'Chuẩn', 	
								NTIS_REPLY:'Trả lời', 	
								NTIS_REPLY_ALL:'Trả lời tất cả', 	
								NTIS_DOWNLOAD:'Tải tập tin đính kèm', 	
								NTIS_DELETE_WEBMAIL:'Xóa', 	
								DELETE:'Số luợng bạn muốn xóa là  ', 	
                                RECORDS:' phải không ?', 	
                                SELECT:'Vui lòng chọn ít nhất một tin !!!', 	
                                DELETE_ACCOUNT:'Việc xóa Khách hàng này sẽ loại bỏ những Cơ hội và báo giá liên quan.\nSố luợng bạn muốn xóa là ', 	
                                DELETE_VENDOR:'Việc xóa nhà cung cấp này sẽ loại bỏ những nhập hàng liên quan.\nSố luợng bạn muốn xóa là ', 	
                                SELECT_MAILID:'Hãy chọn mã thư !!!', 	
                                OVERWRITE_EXISTING_ACCOUNT1:'Ghi đè lên địa chỉ đã có của Khách hàng (', 	
                                OVERWRITE_EXISTING_ACCOUNT2:') với những thông tin địa chỉ mới sau ?', 	
                                OVERWRITE_EXISTING_CONTACT1:'Ghi đè lên địa chỉ đã có của liên hệ (',
                                OVERWRITE_EXISTING_CONTACT2:') với những thông tin địa chỉ mới sau ?',
                                MISSING_FIELDS:'Thiếu trường (cần thiết) ', 	
                                NOT_ALLOWED_TO_EDIT:'bạn không được phép sửa trường này', 	
                                COLUMNS_CANNOT_BE_EMPTY:'Cột đã chọn không được rỗng', 	
                                CANNOT_BE_EMPTY:' không thể thiếu !!!', 	
                                CANNOT_BE_NONE:' không thể không có', 	
                                ENTER_VALID:'Bạn vui lòng nhập lại  ', 	
                                SHOULDBE_LESS:' phải nhỏ hơn ', 	
                                SHOULDBE_LESS_EQUAL:' phải nhỏ hơn hay bằng ', 	
                                SHOULDBE_EQUAL:' phải bằng ', 	
                                SHOULDBE_GREATER:' phải lớn hơn ', 	
                                SHOULDBE_GREATER_EQUAL:' phải lớn hơn hay bằng ', 	
                                INVALID:'Có lỗi đối với ', 	
                                EXCEEDS_MAX:' vượt quá giới hạn lớn nhất ', 	
                                OUT_OF_RANGE:' ra ngoài phạm vi', 	
                                SHOULDNOTBE_EQUAL:' không được bằng ', 	
                                PORTAL_PROVIDE_EMAILID:'Bạn hãy nhập vào thông tin email của khách hàng để hệ thống có thể gửi thông tin đăng nhập', 	
                                ADD_CONFIRMATION:'Số lượng bạn muốn thêm là ', 	
                                ACCOUNTNAME_CANNOT_EMPTY:'Tên Khách hàng không thể thiếu', 	
                                CANT_SELECT_CONTACTS:"Không thể chọn vì bạn đã chọn đầu mối.\n(Đầu mối và người liên hệ không liên quan với nhau)^_^", 	
                                LBL_THIS:'Đây là ', 	
                                DOESNOT_HAVE_MAILIDS:"  không có mã thư nào", 	
                                ARE_YOU_SURE:'Bạn có chắc không ?', 	
                                DOESNOT_HAVE_AN_MAILID:'" '+"không có mã thư", 	
                                MISSING_REQUIRED_FIELDS:'Thiếu trường ', 	
                                READONLY:"chỉ đọc", 	
								SELECT_ATLEAST_ONE_USER:'Hãy chọn ít nhất một người dùng !!!', 	
                                DISABLE_SHARING_CONFIRMATION:'Bạn muốn vô hiệu việc dùng chung cho lựa chọn', 	
                                USERS:' người dùng nào ?', 	
                                ENDTIME_GREATER_THAN_STARTTIME:'Thời điểm kết thúc phải lớn hơn thời điểm bắt đầu ', 	
                                FOLLOWUPTIME_GREATER_THAN_STARTTIME:'thời điểm diễn ra phải lớn hơn thời điểm bắt đầu ', 	
                                MISSING_EVENT_NAME:'Thiếu tên sự kiện', 	
                                EVENT_TYPE_NOT_SELECTED:'Trường tên của cơ hội không được trống', 	
                                OPPORTUNITYNAME_CANNOT_BE_EMPTY:'Trường tên của cơ hội không được trống', 	
                                CLOSEDATE_CANNOT_BE_EMPTY:'Trường ngày kết thúc không được trống', 	
                                SITEURL_CANNOT_BE_EMPTY:'Trang URL không được trống', 	
                                SITENAME_CANNOT_BE_EMPTY:'Tên trang không được trống', 	
                                LISTPRICE_CANNOT_BE_EMPTY:'Đơn giá không được trống', 	
                                INVALID_LIST_PRICE:'Đơn giá không hợp lệ', 	
                                PROBLEM_ACCESSSING_URL:'Bị trục trặc khi truy cập URL ', 	
                                CODE:' Mã ', 	
                                WISH_TO_QUALIFY_MAIL_AS_CONTACT:'Bạn muốn làm cho thư này như là một liên hệ phải không ?', 	
                                SELECT_ATLEAST_ONEMSG_TO_DEL:'Vui lòng chọn ít nhất một tin để xóa !!!', 	
                                ERROR:'Lỗi', 	
                                FIELD_TYPE_NOT_SELECTED:'Kiểu trường chưa được chọn', 	
                                SPECIAL_CHARACTERS_NOT_ALLOWED:'Ký tự đặc biệt không được cho phép trong trường nhãn', 	
                                PICKLIST_CANNOT_BE_EMPTY:'Giá trị danh sách chọn không được trống', 	
                                DUPLICATE_VALUES_FOUND:'Sao chép giá trị tìm thấy', 	
                                DUPLICATE_MAPPING_ACCOUNTS:'Tạo bản sao cho Khách hàng !!', 	
                                DUPLICATE_MAPPING_CONTACTS:'Tạo bản sao cho liên hệ !!', 	
                                DUPLICATE_MAPPING_POTENTIAL:'Tạo bản sao cho Cơ hội !!', 	
                                ERROR_WHILE_EDITING:'Lỗi khi soạn thảo', 	
                                CURRENCY_CHANGE_INFO:'Chuyển đổi đơn vị tiền tệ thành công', 	
                                CURRENCY_CONVERSION_INFO:'Phải Bạn đang dùng Dollar $ làm đơn vị tiền tệ ?\n  Nhấn Đồng ý để giữ nguyên là $, Thoát để chuyển đổi đơn vị tiền tệ khác.', 	
                                THE_EMAILID: "Mã của thư điện tử \'", 	
                                EMAIL_FIELD_INVALID:"\' trong trường thư là không hợp lệ", 	
                                MISSING_REPORT_NAME:'Thiếu tên báo cáo', 	
                                REPORT_NAME_EXISTS:'Tên báo cáo đã có. Hãy thử lại...', 	
                                WANT_TO_CHANGE_CONTACT_ADDR:'Bạn có muốn thay đổi địa chỉ của liên hệ liên quan tới Khách hàng này không ?', 	
                                SURE_TO_DELETE:'Bạn muốn xóa mẫu tin này chứ ?', 	
           						NO_PRODUCT_SELECTED:'Không có sản phẩm nào được chọn. Hãy chọn ít nhất một sản phẩm !!!', 	
                                VALID_FINAL_PERCENT:'Nhập tỷ lệ phần trăm chiết khấu thích hợp', 	
                                VALID_FINAL_AMOUNT:'Nhập lượng chiết khấu thích hợp', 	
                                VALID_SHIPPING_CHARGE:'Nhập phí vận chuyển và đóng gói thích hợp', 	
                                VALID_ADJUSTMENT:'Nhập một điều chỉnh thích hợp', 	
                                WANT_TO_CONTINUE:'Bạn muốn tiếp tục nữa không ?', 	
                                ENTER_VALID_TAX:'Hãy nhập giá trị thuế thích hợp', 	
                                VALID_TAX_NAME:'Nhập tên thuế thích hợp', 	
                                CORRECT_TAX_VALUE:'Nhập giá trị thuế đúng', 	
                                ENTER_POSITIVE_VALUE:'Hãy nhập giá trị rõ ràng', 	
                                LABEL_SHOULDNOT_EMPTY:'Tên nhãn của thuế không được trống', 	
                                NOT_VALID_ENTRY:'mục nhập không hợp lệ. Hãy nhập giá trị đúng', 	
                                VALID_DISCOUNT_PERCENT:'Nhập vào phần trăm giảm giá thích hợp', 	
                                VALID_DISCOUNT_AMOUNT:'Nhập vào lượng giảm giá thích hợp', 	
                                SELECT_TEMPLATE_TO_MERGE:'Hãy chọn một mẫu để ghép !!!', 	
              					SELECTED_MORE_THAN_ONCE:'Bạn đã chọn những sản phẩm này hơn một lần.', 	
           						YES:'có', 	
                                NO:'không', 	
                                MAIL:'thư', 	
								EQUALS:'bằng', 	
								NOT_EQUALS_TO:'không bằng', 	
								CONTAINS:'chứa', 	
								DOES_NOT_CONTAINS:'không chứa', 	
								STARTS_WITH:'bắt đầu với', 	
								ENDS_WITH:'kết thúc với', 	
								LESS_THAN:'nhỏ hơn', 	
								GREATER_THAN:'lớn hơn', 	
								LESS_OR_EQUALS:'nhỏ hơn hay bằng', 	
								GREATER_OR_EQUALS:'lớn hơn hay bằng', 	
	
								NO_SPECIAL_CHARS:'Ký tự đặc biệt không được cho phép trong chuỗi hóa đơn', 	
								SHARED_EVENT_DEL_MSG:'Người dùng không có quyền để xóa mẫu tin này.', 	
								PLS_SELECT_VALID_FILE:'Hãy chọn tập tin với phần mở rộng:\n', 	
                          		NO_SPECIAL:'Ký tự đặc biệt không được cho phép', 	
								IN_PROFILENAME:' trong tên của lý lịch', 	
								IN_GROUPNAME:' trong tên nhóm', 	
								IN_ROLENAME:' trong tên vai trò', 	
                  				VALID_TAX_PERCENT:'Nhập vào tỷ lệ phần trăm thuế', 	
                                VALID_SH_TAX:'Nhập vào giá trị thuế vận chuyển và đóng gói ', 	
								ROLE_DRAG_ERR_MSG:'Bạn không thể chuyển nút cha xuống dưới nút con', 	
								LBL_DEL:'xóa', 	
								VALID_DATA :' Vui lòng thử lại và nhập vào dữ liệu hợp lệ !!! ', 	
                                STDFILTER : 'Lọc chuẩn', 	
                                STARTDATE : 'Ngày bắt đầu', 	
                                ENDDATE : 'Ngày kết thúc', 	
                                START_DATE_TIME : 'Ngày giờ bắt đầu', 	
                                START_TIME : 'Bắt đầu lúc', 	
                                DATE_SHOULDNOT_PAST :'Ngày và giờ hiện tại để hoạt động ở trạng thái được lên kế hoạch', 	
                                TIME_SHOULDNOT_PAST :'Thời điểm hiện tại để hoạt động ở trang thái đã lên kế hoạch', 	
								LBL_AND : 'Và', 	
								LBL_ENTER_VALID_PORT: 'Hãy nhập vào mã số cổng', 	
								IN_USERNAME :' trong Người dùng ', 	
								LBL_ENTER_VALID_NO: 'Hãy nhập vào số hiệu hợp lệ', 	
								LBL_PROVIDE_YES_NO: ' Giá trị không hợp lệ.\n Vui lòng cho quyết định có hay không !!!', 	
								LBL_SELECT_CRITERIA: ' giá trị tiêu chuẩn.\n Hãy chọn tiêu chuẩn !!!', 	
								// Added/Updated for vtiger CRM 5.0.4 	
								OPPORTUNITYNAME_CANNOT_BE_EMPTY:'Trường tên của Cơ hội không thể trống', 	
				                OVERWRITE_EXISTING_ACCOUNT1:'Ghi chồng lên địa chỉ đang tồn tại ở phần địa chỉ của Khách hàng (', 	
				                NAME_DESC:' cho tên thư mục và mô tả', 	
				
				                SHARED_EVENT_DEL_MSG:'Người dùng không có quyền để sửa và xóa sự kiện chung.', 	
					
	
								LBL_WRONG_IMAGE_TYPE: 'Kiểu tập tin cho phép của liên hệ là kiểu jpeg, png, jpg, gif, pjpeg hay x-png ', 	
								SELECT_MAIL_MOVE: 'Hãy chọn một thư rồi chuyển !!!', 	
         	
								LBL_NOTSEARCH_WITHSEARCH_ALL:'Bạn hãy dùng chức năng tìm kiếm. Tất cả các dòng tin sẽ xuất trong', 	
								LBL_NOTSEARCH_WITHSEARCH_CURRENTPAGE:'Bạn hãy thực hiện tìm kiếm. Bạn có thể dùng chức năng tìm kiếm với dấu & để xuất ra trang này ', 	
								LBL_NO_DATA_SELECTED:'Không có dòng nào được chọn. Hãy chọn ít nhất một dòng để xuất ra !!!', 	
								LBL_SEARCH_WITHOUTSEARCH_ALL:'Bạn đã dùng lựa chọn tìm kiếm nhưng bạn đã không chọn tùy chọn "không tìm và lấy hết .\n Bạn nhấn [Đồng ý] để xuất ra hay nhấn [thoát] rồi thử lại với những tiêu chuẩn khác', 	
								STOCK_IS_NOT_ENOUGH : 'Hàng trong kho không đủ', 	
								INVALID_QTY : 'Số lượng phải là kiểu số', 	
								LBL_SEARCH_WITHOUTSEARCH_CURRENTPAGE:'Bạn đã dùng lựa chọn tìm kiếm nhưng bạn đã không chọn tùy chọn "không tìm và trang này.\nBạn nhấn [Đồng ý] để xuất ra hay nhấn [thoát] rồi thử lại với những tiêu chuẩn khác.',
								LBL_SELECT_COLUMN: 'cột không hợp lệ. \ N Vui lòng chọn cột',
								LBL_NOT_ACCESSIBLE: 'Không thể',
								LBL_FILENAME_LENGTH_EXCEED_ERR: 'Tên tập tin không thể vượt quá 255 ký tự',
								LBL_DONT_HAVE_EMAIL_PERMISSION: "Bạn không có quyền với trường email để bạn có thể chọn email id",
								LBL_NO_FEEDS_SELECTED: 'Không có nguồn cấp dữ liệu được chọn',
								LBL_SELECT_PICKLIST: 'Xin vui lòng lựa chọn ít nhất một trong những giá trị để xóa',
								LBL_CANT_REMOVE: 'Bạn có thể \' t loại bỏ tất cả các giá trị ',
				// Added after 5.0.4 GA
				
				/*For global add/delete in picklist*/
				LBL_GIVE_PICKLIST_VALUE: 'Xin vui lòng cung cấp một số giá trị cho danh sách chọn được lựa chọn để được thay thế',
				LBL_SELECT_ROLE: 'Xin vui lòng lựa chọn ít nhất một trong những vai trò mà các giá trị mới sẽ được thêm vào',
				LBL_ADD_PICKLIST_VALUE: 'Xin vui lòng cung cấp ít nhất một giá trị mới để thêm vào',
				LBL_NO_VALUES_TO_DELETE: "không có giá trị để xóa bỏ",

                /* For Duplicate merging feature */
				SAME_GROUPS: 'Bạn có để lựa chọn các dòng trong cùng một nhóm để hợp nhất',
				ATLEAST_TWO: 'Chọn ít nhất hai dòng để hợp nhất',
				MAX_THREE: 'Bạn được phép chọn tối đa ba dòng',
				//PARENT_RECORD: 'Select a record as parent record',  MergeFields.tpl Line:59
				MAX_RECORDS: 'Bạn được phép chọn tối đa bốn dòng',
				CON_MANDATORY: 'Chọn trường bắt buộc tên',
				LE_MANDATORY: 'Chọn trường bắt buộc tên và công ty',
				ACC_MANDATORY: 'Chọn trường bắt buộc khách hàng',
				PRO_MANDATORY: 'Chọn trường bắt buộc tên sản phẩm',
				TIC_MANDATORY: 'Chọn trường bắt buộc tiêu đề phiếu hỗ trợ',
				POTEN_MANDATORY: 'Chọn trường bắt buộc tên tiềm năng',
				VEN_MANDATORY: 'Chọn trường bắt buộc tên nhà cung cấp',
				DEL_MANDATORY: 'Bạn không được phép xóa trường bắt buộc',

		
				/* For Multi-Currency Support */
				MSG_CHANGE_CURRENCY_REVISE_UNIT_PRICE: 'Đơn vị giá cả của tất cả các loại tiền tệ sẽ được sửa đổi dựa trên các lựa chọn của bạn. Bạn có chắc chắn? ',
				
				Select_one_record_as_parent_record: 'Chọn một bản ghi như là bản ghi cha để ghi',
				RECURRING_FREQUENCY_NOT_PROVIDED: 'Trùng lặp tần số không được cung cấp',
				RECURRING_FREQNECY_NOT_ENABLED: 'Trùng lặp tần số được cung cấp, định kỳ, nhưng chưa được kích hoạt',
				
				
				/* Added for Documents module */
				
				NO_SPECIAL_CHARS_DOCS: 'Các ký tự đặc biệt như dấu ngoặc kép, dấu chéo, + biểu tượng, % và dấu ? không được phép ',
				FOLDER_NAME_TOO_LONG: 'Tên thư mục quá dài. Hãy thử lại! ',
				FOLDERNAME_EMPTY: 'Các tên thư mục không thể để trống',
				DUPLICATE_FOLDER_NAME: 'Tên thư mục bị trùng. Xin vui lòng thử lại! ',
				FOLDER_DESCRIPTION_TOO_LONG: 'Phần mô tả của thư mục quá dài. Hãy thử lại! ',
				NOT_PERMITTED: "Bạn không được phép thực hiện thao tác này.",			
	
				ALL_FILTER_CREATION_DENIED: 'Bạn không thể tạo tên bộ lọc với tên tiếng anh là All',
				OPERATION_DENIED: 'Bạn bị từ chối khi thực hiện thao tác này',
				EMAIL_CHECK_MSG: 'Quyền truy cập vào cổng người dùng không thể cấp được bởi vì người dùng chưa có địa chỉ email ',
				IS_PARENT: 'Sản phẩm này có sản phẩm cấp dưới, Bạn không được phép chọn nguồn cho các sản phẩm này ',				
				/*global actions on picklist*/
			
				PICKLIST_CANNOT_BE_EMPTY: 'Giá trị của danh sách chọn không thể để trống',
				DUPLICATE_VALUES_FOUND: 'Tìm thấy các giá trị trùng',
				LBL_NO_ROLES_SELECTED: 'Không có vai trò nào được lựa chọn, bạn có muốn tiếp tục không?',
				LBL_DUPLICATE_FOUND: 'Sao chép mục được tìm thấy cho giá trị',
				LBL_CANNOT_HAVE_EMPTY_VALUE: 'Không thể thay thế bằng giá trị trống, để xóa bạn hãy dùng chức năng xóa.',
				LBL_DUPLICATE_VALUE_EXISTS: 'Tồn tại giá trị trùng ',
				LBL_WANT_TO_DELETE: "Điều này sẽ xóa các giá trị trong danh sách đã lựa chọn trong tất cả các vai trò. Bạn chắc chắn muốn tiếp tục không?",
				LBL_DELETE_ALL_WARNING: "Phải có ít nhất một giá trị cho danh sách chọn",
				LBL_PLEASE_CHANGE_REPLACEMENT: "xin vui lòng thay đổi các giá trị thay thế, nó cũng được chọn để xóa bỏ", 			
								
				/*layout Editor changes*/		
				BLOCK_NAME_CANNOT_BE_BLANK: 'Tên của khối không thể trống',
				ARE_YOU_SURE_YOU_WANT_TO_DELETE: 'Bạn có chắc chắn muốn xoá không?',
				PLEASE_MOVE_THE_FIELDS_TO_ANOTHER_BLOCK: 'Xin vui lòng chuyển các trường này đến khối khác',
				ARE_YOU_SURE_YOU_WANT_TO_DELETE_BLOCK: 'Bạn có chắc chắn muốn xóa khối?',
				LABEL_CANNOT_NOT_EMPTY: 'Nhãn không thể để trống',
				LBL_TYPEALERT_1: 'Xin lỗi, bạn có thể không thể ánh xạ',
				
				LBL_WITH: 'với',
				LBL_TYPEALERT_2: 'loại dữ liệu. Vui lòng ánh xạ cùng loại dữ liệu. ',
				LBL_LENGTHALERT: 'Xin lỗi, bạn không thể ánh xạ các trường này khi kích cỡ các ký tự khác nhau. Vui lòng ánh xạ các dữ liệu với cùng một kiểu hoặc kích thước ký tự. ',
				LBL_DECIMALALERT: 'Xin lỗi, bạn không thể ánh xạ các trường này khi khác dấu thập phân. Vui lòng ánh xạ các dữ liệu với cùng một kiểu hoặc cùng dấu thập phân',
				FIELD_IS_MANDATORY: 'Trường bắt buộc ',
				FIELD_IS_ACTIVE: 'Trường đã sẵn sàng để sử dụng ',
				FIELD_IN_QCREATE: 'Xuất hiện trong menu tạo nhanh ',
				FIELD_IS_MASSEDITABLE: 'Sẵn sàng cho chức năng sửa nhanh',			
		
				IS_MANDATORY_FIELD : 'là trường bắt buộc',
				CLOSEDATE_CANNOT_BE_EMPTY : 'Thời gian kết thúc dự kiến không được rỗng',
				AMOUNT_CANNOT_BE_EMPTY: 'Số tiền không được trống',
				ARE_YOU_SURE: 'Bạn có chắc chắn muốn xoá?',
				LABEL_ALREADY_EXISTS: 'Nhãn đã tồn tại. Xin vui lòng chỉ định một nhãn khác ',
				LENGTH_OUT_OF_RANGE: 'Độ dài của các khối nên ít hơn 50 ký tự ',
				LBL_SELECT_ONE_FILE: 'Xin vui lòng lựa chọn ít nhất một tập tin',
				LBL_UNABLE_TO_ADD_FOLDER: 'Không thể thêm thư mục. Xin vui lòng thử lại. ',
				LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE_FOLDER: 'Bạn có chắc chắn muốn xóa thư mục này?',
				LBL_ERROR_WHILE_DELETING_FOLDER: 'Lỗi trong khi xóa các thư mục.Vui lòng thử lại sau.', 			
									
				LBL_FILE_CAN_BE_DOWNLOAD: 'Tập tin đã sẵn sàng để tải về',
				LBL_DOCUMENT_LOST_INTEGRITY: 'Văn bản này không có sẵn. Nó sẽ được đánh dấu là không hoạt động ',
				LBL_DOCUMENT_NOT_AVAILABLE: 'tài liệu này không sẵn sàng cho tải',
				LBL_FOLDER_SHOULD_BE_EMPTY: 'Thư mục phải rỗng mới có thể xóa bỏ!',
				
				LBL_PLEASE_SELECT_FILE_TO_UPLOAD: 'Xin vui lòng lựa chọn tập tin để tải lên.',
				LBL_ARE_YOU_SURE_TO_MOVE_TO: 'Bạn có chắc là bạn muốn di chuyển các tập tin đến ',
				LBL_FOLDER: 'thư mục',
				LBL_UNABLE_TO_UPDATE: 'Không thể cập nhật! Xin vui lòng thử lại. ',
				LBL_BLANK_REPLACEMENT: "Không thể chọn giá trị trống để thay thế",
				
				LBL_IMAGE_DELETED : 'Ảnh đã bị xóa',
				
				/* Tooltip management */
				ERR_FIELD_SELECTION : 'Có một vài lỗi trong trường lựa chọn',
				
				/* Inventory validation strings */
	
				NO_LINE_ITEM_SELECTED: 'Không có mục dòng được chọn. Xin vui lòng lựa chọn ít nhất một dòng. ',
				LINE_ITEM: 'Mặt hàng ',
				LIST_PRICE: 'Giá',
								
				/* Webmails */
				LBL_PRINT_EMAIL : 'In ra', 
				LBL_DELETE_EMAIL : 'Xóa', 
				LBL_DOWNLOAD_ATTACHMENTS : 'Tải về file đính kèm', 
				LBL_QUALIFY_EMAIL : 'Chuyển thành liên hệ', 
				LBL_FORWARD_EMAIL : 'Gửi đến địa chỉ mới', 
				LBL_REPLY_TO_SENDER : 'Gửi lại cho người gửi', 
				LBL_REPLY_TO_ALL : 'Gửi lại cho tất cả',
				
				LBL_WIDGET_HIDDEN : 'Ẩn Widget',
				LBL_RESTORE_FROM_PREFERENCES : 'Vào phần [Thiết lập cá nhân] để phục hồi',
				ERR_HIDING : 'Xuất hiện lỗi',
				MSG_TRY_AGAIN : 'Vui lòng thử lại',
				
				MSG_ENABLE_SINGLEPANE_VIEW : 'Chế độ xem một trang được bật',
				MSG_DISABLE_SINGLEPANE_VIEW : 'Chế độ xem mộ trang bị tắt',
				
				MSG_FTP_BACKUP_DISABLED : 'Dừng chế độ sao lưu dữ liệu qua FTP',
				MSG_LOCAL_BACKUP_DISABLED : 'Dừng chế độ sao lưu dữ liệu trên máy cục bộ',
				MSG_FTP_BACKUP_ENABLED : 'Khởi động chế độ sao lưu dữ liệu qua FTP',
				MSG_LOCAL_BACKUP_ENABLED : 'Khởi động chế độ sao lưu dữ liệu trên máy cục bộ',
				MSG_CONFIRM_PATH: 'Xác nhận thông tin chi tiết của đường dẫn',
				MSG_CONFIRM_FTP_DETAILS: 'Xác nhận thông tin chi tiết của tài khoản FTP ',
				
				START_PERIOD_END_PERIOD_CANNOT_BE_EMPTY: 'Thời điểm bắt đầu và kết thúc không thể để trống',		
				
				/* added to fix i18n issues with home page*/
				LBL_ADD: 'Thêm ',
				Module: 'Phân hệ',
				DashBoard: 'Biểu đồ',
				RSS: 'Tin nhanh',
				Default: 'Mặc định',
				Notebook: 'Sổ tay',
			};